spring:
  application:
    name: similar-products
  cache:
    cache-names: product-details,similar-ids
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=10m
server:
  port: 5000

logging:
  level:
    org.springframework.cache: DEBUG

external:
  product-api:
    base-url: http://localhost:3001
    connect-timeout-ms: 2000
    read-timeout-ms: 3000

resilience4j:
  circuitbreaker:
    instances:
      productDetails:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
  retry:
    instances:
      productDetails:
        maxAttempts: 2
        waitDuration: 500ms
